import { StyleSheet } from 'react-native';

import { FONT } from '../theme/typography';

export const CARD_SHADOW = {
  shadowColor: '#191c3a',
  shadowOpacity: 0.05,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 6 },
  elevation: 2,
};

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  scroll: { padding: 20, paddingTop: 8, paddingBottom: 56 },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  topRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 4, marginBottom: 18 },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  logo: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  logoText: { color: '#fff', fontFamily: FONT.extrabold, fontSize: 19 },
  footerLogoImage: { width: 26, height: 26, borderRadius: 9 },
  brandName: { fontFamily: FONT.extrabold, fontSize: 17, letterSpacing: -0.2 },
  greet: { fontFamily: FONT.bold, fontSize: 13 },
  title: { fontSize: 21, fontFamily: FONT.extrabold, letterSpacing: -0.4 },
  pageTitle: { fontSize: 26, fontFamily: FONT.extrabold, letterSpacing: -0.5 },
  heroTitle: { fontSize: 26, fontFamily: FONT.extrabold, letterSpacing: -0.5, marginTop: 18 },
  subtitle: { fontSize: 14, fontFamily: FONT.medium, marginTop: 6, lineHeight: 20 },
  iconButton: { width: 40, height: 40, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  ringWrap: { alignItems: 'center', justifyContent: 'center', marginTop: 14, marginBottom: 4 },
  ringCenter: { position: 'absolute', alignItems: 'center' },
  ringLabel: { fontSize: 11, fontFamily: FONT.bold, textTransform: 'uppercase', letterSpacing: 1 },
  ringAmount: { fontSize: 50, fontFamily: FONT.extrabold, letterSpacing: -1.6, marginTop: 4, fontVariant: ['tabular-nums'] },
  ringKhr: { fontSize: 13, fontFamily: FONT.semibold, marginTop: 4 },
  pill: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 999, paddingVertical: 8, paddingHorizontal: 14, marginTop: 8 },
  pillText: { fontSize: 12, fontFamily: FONT.semibold },
  duePill: { paddingVertical: 5, paddingHorizontal: 10, borderRadius: 999 },
  duePillText: { fontSize: 11, fontFamily: FONT.semibold },
  duePillBig: { paddingVertical: 14, paddingHorizontal: 16, borderRadius: 14 },
  card: { borderWidth: 1, borderRadius: 24, padding: 20, marginTop: 16, ...CARD_SHADOW },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 22, marginBottom: 12, paddingHorizontal: 4 },
  sectionTitle: { fontFamily: FONT.bold, fontSize: 13 },
  sectionAction: { fontFamily: FONT.bold, fontSize: 13 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  rowLabel: { fontSize: 13, fontFamily: FONT.medium },
  rowValue: { fontSize: 13, fontFamily: FONT.bold, fontVariant: ['tabular-nums'] },
  track: { height: 9, borderRadius: 99, overflow: 'hidden', marginTop: 7 },
  fill: { height: '100%', borderRadius: 99 },
  expenseRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, borderBottomWidth: 1 },
  bubble: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  bubbleLarge: { width: 52, height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  itemName: { fontFamily: FONT.semibold, fontSize: 14 },
  itemTitle: { fontFamily: FONT.bold, fontSize: 15 },
  itemSub: { fontFamily: FONT.medium, fontSize: 12, marginTop: 1 },
  itemNote: { fontFamily: FONT.medium, fontSize: 12, fontStyle: 'italic', marginTop: 2 },
  amount: { fontFamily: FONT.bold, fontSize: 15, fontVariant: ['tabular-nums'] },
  amountSub: { fontFamily: FONT.medium, fontSize: 11, textAlign: 'right', marginTop: 1 },
  addInput: { borderWidth: 2, borderRadius: 20, padding: 18, fontSize: 18, fontFamily: FONT.semibold },
  aiHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, fontSize: 12 },
  aiHeaderText: { fontFamily: FONT.bold, fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.5 },
  parsedAmount: { fontSize: 38, fontFamily: FONT.extrabold, letterSpacing: -1.1, marginTop: 8, fontVariant: ['tabular-nums'] },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  chip: { flexDirection: 'row', alignItems: 'center', gap: 6, borderWidth: 1.5, borderRadius: 999, paddingVertical: 9, paddingHorizontal: 14 },
  chipText: { fontFamily: FONT.semibold, fontSize: 13 },
  label: { fontSize: 12, fontFamily: FONT.bold, textTransform: 'uppercase', letterSpacing: 0.8, marginTop: 20, marginBottom: 9 },
  input: { borderWidth: 2, borderRadius: 16, padding: 16, fontSize: 18, fontFamily: FONT.bold, fontVariant: ['tabular-nums'] },
  button: { minHeight: 56, borderRadius: 18, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  buttonText: { color: '#fff', fontFamily: FONT.bold, fontSize: 16 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 14 },
  catCard: { width: '48%', borderWidth: 1, borderRadius: 22, padding: 15, ...CARD_SHADOW },
  dashed: { borderWidth: 1.5, borderStyle: 'dashed', borderRadius: 20, padding: 16, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', marginTop: 16 },
  sweep: { borderRadius: 14, padding: 13, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', marginTop: 14 },
  emptyState: { borderWidth: 1, borderRadius: 20, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 10, ...CARD_SHADOW },
  emptyIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  goalBadge: { borderRadius: 14, padding: 12, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', marginTop: 14 },
  statusCard: { borderRadius: 24, padding: 22, marginTop: 14, shadowColor: '#191c3a', shadowOpacity: 0.18, shadowRadius: 20, shadowOffset: { width: 0, height: 12 }, elevation: 5 },
  statusPill: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 6, backgroundColor: 'rgba(255,255,255,.22)', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 999 },
  statusPillText: { color: '#fff', fontFamily: FONT.bold, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.5 },
  statusHeadline: { color: '#fff', fontFamily: FONT.extrabold, fontSize: 24, lineHeight: 30, letterSpacing: -0.3, marginTop: 14, marginBottom: 16 },
  statRow: { flexDirection: 'row', gap: 12 },
  statBox: { flex: 1, backgroundColor: 'rgba(255,255,255,.16)', borderRadius: 16, padding: 13 },
  statValue: { color: '#fff', fontFamily: FONT.extrabold, fontSize: 22, fontVariant: ['tabular-nums'] },
  statLabel: { color: '#fff', fontFamily: FONT.semibold, fontSize: 11, opacity: 0.9, marginTop: 2 },
  tip: { flexDirection: 'row', gap: 11, backgroundColor: 'rgba(255,255,255,.15)', borderRadius: 16, padding: 14, marginTop: 12 },
  tipText: { color: '#fff', fontFamily: FONT.medium, fontSize: 13, lineHeight: 19, flex: 1 },
  chart: { height: 150, flexDirection: 'row', alignItems: 'flex-end', gap: 9, paddingTop: 8 },
  barCol: { flex: 1, alignItems: 'center', justifyContent: 'flex-end', gap: 6 },
  bar: { width: '100%', borderTopLeftRadius: 8, borderTopRightRadius: 8, borderBottomLeftRadius: 3, borderBottomRightRadius: 3 },
  barDay: { fontFamily: FONT.semibold, fontSize: 10 },
  statMini: { flex: 1, borderRadius: 14, padding: 12 },
  settingsRow: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 16, borderBottomWidth: 1 },
  settingsIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  dots: { flexDirection: 'row', alignSelf: 'center', gap: 6, marginVertical: 14 },
  dot: { height: 8, borderRadius: 99 },
  segment: { flexDirection: 'row', borderRadius: 14, padding: 4, gap: 4 },
  segmentButton: { flex: 1, borderRadius: 10, paddingVertical: 11, alignItems: 'center' },
  segmentText: { fontFamily: FONT.bold, fontSize: 13 },
  help: { fontSize: 12, fontFamily: FONT.medium, lineHeight: 18, marginTop: 12 },
  methodCard: { borderWidth: 2, borderRadius: 18, padding: 16, marginTop: 12 },
  footer: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: 20, paddingBottom: 28, borderTopWidth: 1 },
  nav: { height: 76, borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', paddingBottom: 12, paddingTop: 6, paddingHorizontal: 6 },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 },
  navIcon: { width: 56, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  navLabel: { fontFamily: FONT.semibold, fontSize: 11 },
  fab: { width: 56, height: 56, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginTop: -24, marginHorizontal: 10 },
  toast: { position: 'absolute', alignSelf: 'center', bottom: 100, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 14, paddingVertical: 12, paddingHorizontal: 18, shadowColor: '#000', shadowOpacity: 0.35, shadowRadius: 24, shadowOffset: { width: 0, height: 12 }, elevation: 8 },
  toastText: { fontFamily: FONT.bold, fontSize: 13 },
  scrim: { flex: 1, backgroundColor: 'rgba(10,10,20,.42)', justifyContent: 'flex-end' },
  celebrateScrim: { flex: 1, backgroundColor: 'rgba(10,10,20,.45)', alignItems: 'center', justifyContent: 'center', padding: 24 },
  celebrateCard: { alignSelf: 'stretch', borderRadius: 28, padding: 28, alignItems: 'center', shadowColor: '#191c3a', shadowOpacity: 0.25, shadowRadius: 30, shadowOffset: { width: 0, height: 16 }, elevation: 10 },
  celebrateIcon: { width: 76, height: 76, borderRadius: 38, alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  celebrateTitle: { fontFamily: FONT.extrabold, fontSize: 24, letterSpacing: -0.4, textAlign: 'center' },
  celebrateBody: { fontFamily: FONT.medium, fontSize: 15, lineHeight: 22, textAlign: 'center', marginTop: 10 },
  sheet: { borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20, paddingBottom: 28, maxHeight: '88%' },
  grab: { width: 40, height: 4, borderRadius: 99, alignSelf: 'center', marginBottom: 14, opacity: 0.55 },
  sheetTitle: { fontSize: 19, fontFamily: FONT.extrabold, letterSpacing: -0.2 },
  swatch: { width: 38, height: 38, borderRadius: 12, borderWidth: 3, borderColor: 'transparent' },
  curToggle: { flexDirection: 'row', borderRadius: 14, padding: 4, gap: 2 },
  curToggleButton: { width: 42, borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
  iconPick: { width: 46, height: 46, borderRadius: 14, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' },
  pickWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
});
