import { isoDayFromDate, isoMonthFromDay } from "../domain/dates";
import type { AppModel, Drafts } from "./types";

export const RATE = 4100;

export const INITIAL_DAY = isoDayFromDate(new Date());
export const INITIAL_MONTH = isoMonthFromDay(INITIAL_DAY);

export const PALETTE = [
  "#ef8b4f",
  "#f0663f",
  "#e0603a",
  "#e05a8a",
  "#ec4899",
  "#9b6dff",
  "#7c5cff",
  "#8b5cf6",
  "#5b8def",
  "#3ba6d4",
  "#0ea5b7",
  "#14b8a6",
  "#1f9d6b",
  "#5aa84a",
  "#d4b03b",
  "#d98a00",
  "#f59e0b",
  "#b06a4a",
  "#8a8d99",
  "#6d7a8c",
  "#d45b5b",
];

export const DEFAULT_APP_CATEGORIES: AppModel["categories"] = [
  {
    key: "food",
    label: "Food & drinks",
    icon: "restaurant",
    color: "#ef8b4f",
    spentUsd: 0,
    budgetUsd: 120,
  },
  {
    key: "transport",
    label: "Transport",
    icon: "directions-bus",
    color: "#3ba6d4",
    spentUsd: 0,
    budgetUsd: 60,
  },
  {
    key: "bills",
    label: "Bills & utilities",
    icon: "receipt-long",
    color: "#d98a00",
    spentUsd: 0,
    budgetUsd: 100,
  },
  {
    key: "shopping",
    label: "Shopping",
    icon: "shopping-bag",
    color: "#e05a8a",
    spentUsd: 0,
    budgetUsd: 80,
  },
  {
    key: "ent",
    label: "Entertainment",
    icon: "movie",
    color: "#7c5cff",
    spentUsd: 0,
    budgetUsd: 50,
  },
  {
    key: "health",
    label: "Health",
    icon: "medical-services",
    color: "#1f9d6b",
    spentUsd: 0,
    budgetUsd: 40,
  },
  {
    key: "education",
    label: "Education",
    icon: "school",
    color: "#5b8def",
    spentUsd: 0,
    budgetUsd: 30,
  },
  {
    key: "family",
    label: "Family & home",
    icon: "home",
    color: "#5aa84a",
    spentUsd: 0,
    budgetUsd: 50,
  },
  {
    key: "travel",
    label: "Travel",
    icon: "flight",
    color: "#9b6dff",
    spentUsd: 0,
    budgetUsd: 50,
  },
  {
    key: "other",
    label: "Other",
    icon: "category",
    color: "#8a8d99",
    spentUsd: 0,
    budgetUsd: 30,
  },
];

export const INITIAL_MODEL: AppModel = {
  onboarded: false,
  onbStep: 0,
  screen: "onboarding",
  dark: false,
  language: "en",
  salary: 0,
  salaryCur: "USD",
  budgetCycleStartDay: 1,
  rate: RATE,
  exchangeRateLastFetchedDay: null,
  exchangeRateSource: "Manual setup",
  rent: 0,
  utilities: 0,
  loan: 0,
  rentDue: 1,
  loanDue: 15,
  method: "balanced",
  custom: { needs: 45, wants: 25, save: 30 },
  baseCur: "USD",
  swept: false,
  notify: "21:00",
  billReminders: true,
  defaultCategoriesSeeded: true,
  categories: DEFAULT_APP_CATEGORIES,
  expenses: [],
  goals: [],
  ious: [],
  recurringPayments: [],
  history: [],
  rolloverUsd: 0,
  paidBills: {},
  fastEntryMemory: {},
  lastActiveDay: INITIAL_DAY,
  lastActiveMonth: INITIAL_MONTH,
  merchantCorrections: {},
  categoryTrainingExamples: [],
  categoryModelVersion: null,
};

export const INITIAL_DRAFTS: Drafts = {
  addText: "",
  addNote: "",
  transactionKind: "expense",
  selectedCat: "",
  selectedExpenseId: null,
  entryCur: "USD",
  expenseDate: INITIAL_DAY,
  selectedDay: 34,
  transactionSearch: "",
  transactionTypeFilter: "all",
  transactionCategoryFilter: "",
  transactionMonth: "current-cycle",
  categoryName: "",
  categoryBudget: "50",
  categoryIcon: "category",
  categoryColor: PALETTE[0],
  categoryEditKey: null,
  iouPerson: "",
  iouAmount: "",
  iouDue: "",
  iouEditId: null,
  recurringName: "",
  recurringAmount: "",
  recurringCur: "USD",
  recurringDueDay: 1,
  recurringEditId: null,
  goalName: "",
  goalTarget: "",
  goalPer: "",
};
